# CarbonChat Expansion v6.0 - Configuraci√≥n

channel-colors:
  default: "<white>"
  global: "<yellow>"
  chillar: "#ff7d86"
  gritar: "<red>"
  local: "<green>"

channels-with-bubbles:
  - chillar
  - local
